Week9/PatikaMVCLibraryProject/PatikaMVCLibraryProject/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using PatikaMVCLibraryProject.Models;

namespace PatikaMVCLibraryProject.Controllers
{
    public class AuthorController : Controller
    {
        public static List<Author> authors = new List<Author>();

        // Show author list screen 
        [HttpGet]
        public IActionResult List()
        {
            var viewModel = authors.Select(a => new AuthorListViewModel()
            {
                Id = a.Id,
                FirstName = a.FirstName,
                LastName = a.LastName,
                DateOfBirth = a.DateOfBirth,
                Books = a.Books
            }).ToList();

            return View(viewModel);
        }

        // Show create author screen
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // Add an author book
        [HttpPost]
        public IActionResult Create(AuthorCreateViewModel model)
        {
            var newAuthor = new Author
            {
                Id = authors.Any() ? authors.Max(b => b.Id) + 1 : 1,
                FirstName = model.FirstName,
                LastName = model.LastName,
                DateOfBirth = model.DateOfBirth
            };

            authors.Add(newAuthor);

            return RedirectToAction("List");
        }

        // Show edit author screen
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var author = authors.FirstOrDefault(a => a.Id == id);

            if (author == null)
                return NotFound();

            var viewModel = new AuthorEditViewModel()
            {
                Id = author.Id,
                FirstName = author.FirstName,
                LastName = author.LastName,
                DateOfBirth = author.DateOfBirth
            };

            return View(viewModel);
        }

        // Edit an author
        [HttpPost]
        public IActionResult Edit(AuthorEditViewModel updatedAuthor)
        {
            var author = authors.FirstOrDefault(a => a.Id == updatedAuthor.Id);

            if (author == null)
                return NotFound();

            // Update author information
            author.FirstName = updatedAuthor.FirstName;
            author.LastName = updatedAuthor.LastName;
            author.DateOfBirth = updatedAuthor.DateOfBirth;

            //Update AuthorName information in author book list
            foreach (var book in author.Books)
            {
                book.AuthorName = $"{author.FirstName} {author.LastName}";
            }

            return RedirectToAction("List");
        }


        // Show author details screen
        [HttpGet]
        public IActionResult Details(int id)
        {
            var author = authors.FirstOrDefault(a => a.Id == id);

            if (author == null)
                return NotFound();

            return View(author);
        }

        // Show delete author screen
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var author = authors.FirstOrDefault(a => a.Id == id);

            if (author == null) 
                return NotFound();

            if (author.Books.Count != 0)
                ViewBag.error = "Deletion cannot be performed because there are books associating to this author. Before deleting the author, please remove all books associated to the author.";

            return View(author);
        }

        // Delete an author
        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            var author = authors.FirstOrDefault(a => a.Id == id);

            if (author == null)
                return NotFound();

            // Remove from author list
            authors.Remove(author);

            return RedirectToAction("List");
        }
    }
}

Week9/PatikaMVCLibraryProject/PatikaMVCLibraryProject/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PatikaMVCLibraryProject.Models;

namespace PatikaMVCLibraryProject.Controllers
{
    public class BookController : Controller
    {
        public static List<Book> books = new List<Book>();

        // Show book list screen 
        [HttpGet]
        public IActionResult List()
        {
            var viewModel = books.Select(a => new BookListViewModel()
            {
                Id = a.Id,
                Title = a.Title,
                Genre = a.Genre,
                AuthorName = a.AuthorName,
                CopiesAvailable = a.CopiesAvailable
            }).ToList();

            return View(viewModel);
        }

        // Show create book screen
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Authors = AuthorController.authors
                .Select(a => new SelectListItem
                {
                    Value = a.Id.ToString(),
                    Text = $"{a.FirstName} {a.LastName}"
                }).ToList();

            return View();
        }

        // Add a new book
        [HttpPost]
        public IActionResult Create(BookCreateViewModel model)
        {
            var author = AuthorController.authors.FirstOrDefault(a => a.Id == model.AuthorId);

            if (author == null)
                return NotFound();

            var newBook = new Book
            {
                Id = books.Any() ? books.Max(b => b.Id) + 1 : 1,
                Title = model.Title,
                Genre = model.Genre,
                ISBN = model.ISBN,
                PublishDate = model.PublishDate,
                CopiesAvailable = model.CopiesAvailable,
                AuthorId = author.Id,
                AuthorName = $"{author.FirstName} {author.LastName}"
            };

            books.Add(newBook);

            if (author != null)
                author.Books.Add(newBook);

            return RedirectToAction("List");
        }

        // Show edit book screen
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Authors = AuthorController.authors
                .Select(a => new SelectListItem
                {
                    Value = a.Id.ToString(),
                    Text = $"{a.FirstName} {a.LastName}"
                }).ToList();

            var book = books.FirstOrDefault(a => a.Id == id);

            if (book == null)
                return NotFound();

            var author = AuthorController.authors.FirstOrDefault(a => a.Id == book.AuthorId);

            if (author == null)
                return NotFound();

            var viewModel = new BookEditViewModel()
            {
                Id = books.Any() ? books.Max(b => b.Id) + 1 : 1,
                Title = book.Title,
                Genre = book.Genre,
                ISBN = book.ISBN,
                PublishDate = book.PublishDate,
                CopiesAvailable = book.CopiesAvailable,
                AuthorId = author.Id,
                AuthorName = $"{author.FirstName} {author.LastName}"
            };

            return View(viewModel);
        }

        // Edit a book
        [HttpPost]
        public IActionResult Edit(BookEditViewModel updatedBook)
        {
            var book = books.FirstOrDefault(b => b.Id == updatedBook.Id);

            if (book == null)
                return NotFound();

            // Remove from previous author book list 
            var oldAuthor = AuthorController.authors.FirstOrDefault(a => a.Id == book.AuthorId);
            if (oldAuthor != null)
            {
                oldAuthor.Books.Remove(book);
            }

            // Update book information
            book.Title = updatedBook.Title;
            book.Genre = updatedBook.Genre;
            book.ISBN = updatedBook.ISBN;
            book.PublishDate = updatedBook.PublishDate;
            book.CopiesAvailable = updatedBook.CopiesAvailable;
            book.AuthorId = updatedBook.AuthorId;

            // Add to book new author book list
            var newAuthor = AuthorController.authors.FirstOrDefault(a => a.Id == updatedBook.AuthorId);

            if (newAuthor != null)
            {
                book.AuthorName = $"{newAuthor.FirstName} {newAuthor.LastName}";
                newAuthor.Books.Add(book);
            }

            return RedirectToAction("List");
        }


        // Show book details screen
        [HttpGet]
        public IActionResult Details(int id)
        {
            var book = books.FirstOrDefault(b => b.Id == id);

            if (book == null)
                return NotFound();

            return View(book);
        }

        // Show delete book screen
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var book = books.FirstOrDefault(b => b.Id == id);

            if (book == null)
                return NotFound();

            return View(book);
        }

        // Delete a book
        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            var book = books.FirstOrDefault(b => b.Id == id);

            if (book == null)
                return NotFound();

            // Access to author of book and remove from book list
            var author = AuthorController.authors.FirstOrDefault(a => a.Id == book.AuthorId);

            if (author != null)
                author.Books.Remove(book);

            // Remove from book list
            books.Remove(book);

            return RedirectToAction("List");
        }
    }
}

Week9/PatikaMVCLibraryProject/PatikaMVCLibraryProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace PatikaMVCLibraryProject.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

Week9/PatikaMVCLibraryProject/PatikaMVCLibraryProject/Views/Home/About.cshtml
<div class="card mt-3 p-1 text-start">
    <div class="card-header text-center">
        <h1 class="h2 text-primary">About</h1>
    </div>
    <div class="card-body">
        <p>This is a <b>Library Management System</b> built using <b>ASP.NET Core MVC</b>. The system allows users to manage books and authors efficiently.</p>
        <h5>🚀 Purpose</h5>
        <p>The purpose of this project is to create a simple effective library management system that allows users to:</p>
        <ul>
            <li>Efficiently manage books and authors. </li>
            <li>Establish a structured Book-Author relationship</li>
            <li>Provide a user-friendly UI using Bootstrap.  </li>
            <li>Implement CRUD operations for books and authors.</li>
        </ul>
        <br />
        <h5>🎯 Features</h5>
        <ul>
            <li><b>Book Management</b>: Add, edit, delete, list and see details books.</li>
            <li><b>Author Management</b>: Add, edit, delete, list and see details authors.</li>
            <li><b>Book-Author Relationship</b>: Each book is linked to an author.</li>
            <li><b>Bootstrap UI</b>: Responsive design with modern UI.</li>
        </ul>
        <br />
        <h5>🛠 Technologies Used</h5>
        <ul>
            <li><b>Backend</b>: ASP.NET Core MVC, C#</li>
            <li><b>Frontend</b>: Bootstrap</li>
        </ul>
        <br />
        <h5>🏗 Future Enhancements</h5>
        <ul>
            <li>Expanding the project with CRUD operations</li>
            <li>Adding authentication and authorization</li>
            <li>Enhancing UI design</li>
        </ul>
    </div>
</div>

Week9/PatikaMVCLibraryProject/PatikaMVCLibraryProject/Views/Home/Index.cshtml
<div class="text-center py-5 d-flex justify-content-center align-items-center">
    <div class="content-wrapper">
        <h1 class="display-3 fw-bold text-primary">Welcome Library Management System</h1>
        <p class="lead text-secondary">Manage and explore a vast collection of books and authors effortlessly.</p>

        <div class="d-flex justify-content-center gap-3 mt-4">
            <a class="btn btn-primary btn-lg px-4 py-2 shadow-sm rounded-pill" asp-area="" asp-controller="Book" asp-action="List">
                📚 Browse Books
            </a>
            <a class="btn btn-secondary btn-lg px-4 py-2 shadow-sm rounded-pill" asp-area="" asp-controller="Author" asp-action="List">
                ✍️ View Authors
            </a>
        </div>

        <div class="container mt-5">
            <div class="row g-4">
                <div class="col-md-6">
                    <div class="card shadow-sm border-0 h-100">
                        <div class="card-body text-center">
                            <h4 class="text-primary">Discover Books</h4>
                            <p class="text-muted">Explore our collection of books across various genres.</p>
                            <a class="btn btn-outline-primary" asp-area="" asp-controller="Book" asp-action="List">Explore Now</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card shadow-sm border-0 h-100">
                        <div class="card-body text-center">
                            <h4 class="text-secondary">Meet the Authors</h4>
                            <p class="text-muted">Learn more about authors and their works.</p>
                            <a class="btn btn-outline-secondary" asp-area="" asp-controller="Author" asp-action="List">Learn More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>